name: InfiniteBuckets
author: Darrionat
main: me.darrionat.infinitebucket.InfiniteWaterBucket
version: 1.1
description: A custom item that allows an infinite buckets
api-version: 1.13

commands:
  infinitebucket:
    aliases: [ib]
    usage: /<command> [player] [bucketType]
permissions:
  infinitewaterbucket.*:
    description: Gives access to all InfiniteWaterBucket commands
    children:
      infinitewaterbucket.use: true
  infinitewaterbucket.give:
    description: Allows a player to give the infinite water bucket
    default: op