#     ____      _____       _ __          _       __      __               ____             __        __ 
#    /  _/___  / __(_)___  (_) /____     | |     / /___ _/ /____  _____   / __ )__  _______/ /_____  / /_
#    / // __ \/ /_/ / __ \/ / __/ _ \    | | /| / / __ `/ __/ _ \/ ___/  / __  / / / / ___/ //_/ _ \/ __/
#  _/ // / / / __/ / / / / / /_/  __/    | |/ |/ / /_/ / /_/  __/ /     / /_/ / /_/ / /__/ ,< /  __/ /_  
# /___/_/ /_/_/ /_/_/ /_/_/\__/\___/     |__/|__/\__,_/\__/\___/_/     /_____/\__,_/\___/_/|_|\___/\__/  
#     ____           ____                  _                   __ 
#    / __ )__  __   / __ \____ ___________(_)___  ____  ____ _/ /_
#   / __  / / / /  / / / / __ `/ ___/ ___/ / __ \/ __ \/ __ `/ __/
#  / /_/ / /_/ /  / /_/ / /_/ / /  / /  / / /_/ / / / / /_/ / /_  
# /_____/\__, /  /_____/\__,_/_/  /_/  /_/\____/_/ /_/\__,_/\__/  
#       /____/                                                    
name: '&b&lInfinite Water'
lore: 
  - '&7&oMake it rain'
customModelData:
  enabled: false
  data: 1